AWSTemplateFormatVersion: '2010-09-09'
Description: 'Simple S3 Bucket'
Parameters:
  BucketName:
    Type: String
    Description: Name for the S3 bucket
    Default: sc-bucket-example-830088749475
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      Tags:
        - Key: Purpose
          Value: Demo
Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref S3Bucket
